# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a1616d08adc0ef0bc83ec4076c9aa7aa3ffa84e64b2477359c5d8666998547dbf60c88a1aefdb576b97957d63349f42b4ee0fc121bca501ff3a7e3312c2ab53

test:
  secret_key_base: 4460d53bb266d66f6c4a3c563c2547c5117e508868c0a8a8987d14e0b6dd1494b173c7c2af0458f0af79a2b4257ff2c7fcef39d77e1639da5ffa0c80d82e576b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
